name: Publish NuGet Packages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write # important for release description edit and asset upload
  packages: write

jobs:
  publish:
    uses: BigBang1112/workflows/.github/workflows/publish-nuget.yml@main
    with:
      project-path: ChunkL/ChunkL.csproj
      test-path: ChunkL.Tests/ChunkL.Tests.csproj
      dotnet-version: 10.0.x
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
